# Generated by Django 5.1.7 on 2025-10-22 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo', models.CharField(choices=[('citas_diarias', 'Citas Diarias'), ('citas_mensuales', 'Citas Mensuales'), ('estadisticas_doctor', 'Estadísticas por Doctor'), ('estadisticas_paciente', 'Estadísticas por Paciente'), ('ocupacion_clinica', 'Ocupación de Clínica'), ('ingresos', 'Reporte de Ingresos'), ('personalizado', 'Reporte Personalizado')], max_length=30, verbose_name='Tipo de Reporte')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato')),
                ('filtros_aplicados', models.JSONField(default=dict, verbose_name='Filtros Aplicados')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('tamaño_archivo', models.IntegerField(blank=True, null=True, verbose_name='Tamaño en bytes')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
