# Generated by Django 5.1.7 on 2025-10-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20, verbose_name='Estado de la Cita'),
        ),
    ]
