# Generated by Django 5.1.7 on 2025-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('dni', models.CharField(help_text='Documento Personal de Identidad del paciente.', max_length=20, unique=True, verbose_name='DNI / ID')),
                ('historial_medico_basico', models.TextField(blank=True, help_text='Alergias conocidas, condiciones preexistentes, medicación actual relevante, etc.', null=True, verbose_name='Historial Médico Básico')),
                ('informacion_contacto', models.TextField(blank=True, help_text='Teléfono, email, dirección, contacto de emergencia, etc.', null=True, verbose_name='Información de Contacto')),
                ('prioridad', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('U', 'Urgente')], default='B', help_text='Nivel de prioridad para la atención del paciente.', max_length=1, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
