# Generated by Django 5.1.7 on 2025-10-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Doctor Activo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='duracion_cita_default',
            field=models.IntegerField(default=30, verbose_name='Duración Default de Cita (min)'),
        ),
    ]
