# Generated by Django 5.1.7 on 2025-10-22 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Clínica')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de Clínica')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('horario_inicio', models.TimeField(default='08:00', verbose_name='Horario de Inicio')),
                ('horario_fin', models.TimeField(default='18:00', verbose_name='Horario de Fin')),
                ('dias_laborales', models.CharField(default='1,2,3,4,5', max_length=20, verbose_name='Días Laborales (1=Lun, 7=Dom)')),
                ('duracion_cita_default', models.IntegerField(default=30, verbose_name='Duración Default de Cita (min)')),
                ('max_citas_por_dia', models.IntegerField(default=50, verbose_name='Máximo Citas por Día')),
                ('activa', models.BooleanField(default=True, verbose_name='Clínica Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador Principal')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('recepcionista', 'Recepcionista'), ('enfermera', 'Enfermera')], max_length=20, verbose_name='Rol en la Clínica')),
                ('activo', models.BooleanField(default=True, verbose_name='Acceso Activo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Clínica',
                'verbose_name_plural': 'Usuarios de Clínicas',
                'unique_together': {('usuario', 'clinica')},
            },
        ),
    ]
